import { AppDataSource } from "./data-source"
import { Rider } from "./entity/Rider"
import { Express, Request, Response } from "express";
import express = require("express");

const app: Express = express();
const port = 3000;

app.get("/", (req: Request, res: Response) => {
    res.send("Express + TypeScript Server");
});

app.listen(port, () => {
    console.log(`[server]: Server is running at http://localhost:${port}`);
});

// Dummy initialization autogenerated by typeorm will be replaced with real initialization
AppDataSource.initialize().then(async () => {

    console.log("Inserting a new user into the database...")
    const rider = new Rider()
    rider.firstName = "Timber"
    rider.lastName = "Saw"
    rider.age = 25
    await AppDataSource.manager.save(rider)
    console.log("Saved a new user with id: " + rider.id)

    console.log("Loading users from the database...")
    const riders = await AppDataSource.manager.find(Rider)
    console.log("Loaded users: ", riders)

    console.log("Here you can setup and run express / fastify / any other framework.")

}).catch(error => console.log(error))
