import { AppDataSource } from "./data-source"
import { Express, Request, Response } from "express";
import express = require("express");
import riderRoutes from "./routes/riderRoutes";
import carRoutes from "./routes/carRoutes";
import driverRoutes from "./routes/driverRoutes";
import rideRoutes from "./routes/rideRoutes";

const app: Express = express();
const port = 3000;

// Dummy initialization autogenerated by typeorm will be replaced with real initialization
AppDataSource.initialize().then(async () => {
    console.log("Datasource has been initialized.");
}).catch(error => console.log(error))

app.use(express.json());

app.use("/api/rider", riderRoutes);
app.use("/api/car", carRoutes);
app.use("/api/driver", driverRoutes);
app.use("/api/ride", rideRoutes);

app.get("/", (req: Request, res: Response) => {
    res.send("Express + TypeScript Server");
});

app.listen(port, () => {
    console.log(`[server]: Server is running at http://localhost:${port}`);
});
